### ISSUE TITLE
onnx->trt fail on mobilenet

### ISSUE THREAD

**Issue by VertexC** [VertexC/dl-infer-perf#3]
```bash
root@ubuntu1804-lts-base:/scratch/dev/dev/dl-infer-perf# python3 infer_perf/onnx2trt.py mobilenet
[TensorRT] ERROR: Network must have at least one output
Traceback (most recent call last):
  File "infer_perf/onnx2trt.py", line 80, in <module>
    runner = onnx2trt_runner(args.model, batch_size=args.batch)
  File "infer_perf/onnx2trt.py", line 60, in onnx2trt_runner
    context = engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```

**Comment by VertexC** [comment]
The error has something to do onnx's model version and current trt verison. Need further investigation.

**Comment by VertexC** [comment]
https://forums.developer.nvidia.com/t/whether-tensorrt-supports-mobilenet-in-onnx-framework/80397
